# 1. Importing Necessary Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
import pickle
import matplotlib.pyplot as plt

# 2. SelectK algorithm function

In [2]:
def selectkbest(indep_X,dep_Y,n):
    test = SelectKBest(score_func=chi2,k=n)
    fit1 = test.fit(indep_X,dep_Y)
    selectk_features = fit1.transform(indep_X)
    return selectk_features

# 3. Train test split and Standard Scaler Function

In [3]:
def split_scaler(indep_X,dep_Y):
    X_train,X_test,y_train,y_test = train_test_split(indep_X,dep_Y,test_size=0.25,random_state=0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train,X_test,y_train,y_test

# 4. Evaluation Metrics Function

In [4]:
def r2_prediction(regressor, X_test,y_test):
    y_pred = regressor.predict(X_test)
    from sklearn.metrics import r2_score
    r2 = r2_score(y_test,y_pred)
    return r2

# 5. Regression Models

***1. Linear Regression***

In [5]:
def linear(X_train,y_train,X_test):
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

***2. SVM Linear***

In [6]:
def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'linear')
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

***3. SVM Non-Linear***

In [7]:
def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'rbf')
    regressor.fit(X_train,y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

***4. Decison Tree***

In [8]:
def Decision(X_train,y_train,X_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor = DecisionTreeRegressor(random_state = 0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

***5. Random Forest***

In [9]:
def random(X_train,y_train,X_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

# 6. Creating Table to store the R-squared values of all algorithms

In [10]:
def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Linear','SVMl','SVMnl','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Linear'][idex]=acclin[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

# 7. Loading Dataset and Preprocessing

In [11]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2,dtype=int,drop_first=True)
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [12]:
indep_X = df2.drop('classification_yes', axis=1)
dep_Y = df2['classification_yes']

In [13]:
import warnings 
warnings.filterwarnings('ignore')

# 8. SelectK algorithm Implementation

In [26]:
kbest=selectkbest(indep_X,dep_Y,8) 

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [27]:
X_train, X_test, y_train, y_test=split_scaler(kbest,dep_Y)

for i in kbest:   
    r2_lin = linear(X_train,y_train,X_test)
    acclin.append(r2_lin)
    
    r2_sl = svm_linear(X_train,y_train,X_test)    
    accsvml.append(r2_sl)
    
    r2_NL = svm_NL(X_train,y_train,X_test)
    accsvmnl.append(r2_NL)
    
    r2_d = Decision(X_train,y_train,X_test)
    accdes.append(r2_d)
    
    r2_r = random(X_train,y_train,X_test)
    accrf.append(r2_r)
    
result = selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)

In [19]:
#4 
result

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.304963  0.256858  0.430795  0.479167  0.599392

In [22]:
# 5 
result

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.551985  0.545395  0.749654  0.696181  0.836806

In [25]:
#6
result

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.599041  0.586446  0.838962  0.869792  0.897569

In [ ]:
#7
result

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.657035  0.641906  0.893007  0.826389  0.916233

In [28]:
#8
result

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.646457  0.612199  0.891274  0.869792  0.898872

***Choose SelectK = 7 as it has best R-squared score***