## 1. Importing Necessary Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
import pickle
import matplotlib.pyplot as plt

## 2. Defining function for RFE feature

In [2]:
def rfeFeature(indep_X,dep_Y,n):
        rfelist=[]
        
        from sklearn.linear_model import LinearRegression
        lin = LinearRegression()
        
        from sklearn.svm import SVR
        SVRl = SVR(kernel = 'linear')
        
        from sklearn.tree import DecisionTreeRegressor
        dec = DecisionTreeRegressor(random_state = 0)
        
        from sklearn.ensemble import RandomForestRegressor
        rf = RandomForestRegressor(n_estimators = 10, random_state = 0)
        
        rfemodellist=[lin,SVRl,dec,rf] 
        for i in   rfemodellist:
            print(i)
            log_rfe = RFE(estimator=i, n_features_to_select=n)
            log_fit = log_rfe.fit(indep_X,dep_Y)
            log_rfe_feature=log_fit.transform(indep_X)
            rfelist.append(log_rfe_feature)
        return rfelist

## 3. Combining Standard scalar and train test spilt method function

In [3]:
def split_scaler(indep_X,dep_Y):
    X_train,X_test,y_train,y_test = train_test_split(indep_X,dep_Y,test_size =0.25, random_state = 0)
    sc=StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train,X_test,y_train,y_test

## 4. R2 score function

In [4]:
def r2_prediction(regressor,X_test,y_test):
    y_pred = regressor.predict(X_test)
    from sklearn.metrics import r2_score
    r2 = r2_score(y_test,y_pred)
    return r2

# 5. Regression Models Function

***Linear Regression***

In [5]:
def Linear(X_train,y_train,X_test,y_test):
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(X_train,y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

***SVM - linear***

In [6]:
def svm_linear(X_train,y_train,X_test,y_test):
    from sklearn.svm import SVR
    regressor = SVR(kernel='linear')
    regressor.fit(X_train,y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

***Decision Tree***

In [7]:
def Decision(X_train,y_train,X_test,y_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor = DecisionTreeRegressor(random_state = 0)
    regressor.fit(X_train, y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return  r2

***Random Forest***

In [8]:
def random(X_train,y_train,X_test,y_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators =10,random_state=0)
    regressor.fit(X_train,y_train)
    r2 = r2_prediction(regressor,X_test,y_test)
    return r2

## 6. Creating Table for RFE

In [9]:
def rfe_regression(acclin, accsvml, accdes, accrf):
    rfedataframe = pd.DataFrame({
        'Linear': acclin,
        'SVMl': accsvml,
        'Decision': accdes,
        'Random': accrf
    },index=['Linear', 'SVC', 'Random', 'Decision Tree'])

    return rfedataframe

## 7. Implementation

In [16]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2,dtype=int,drop_first=True)

indep_X=df2.drop('classification_yes', axis=1)
dep_Y=df2['classification_yes']


rfelist = rfeFeature(indep_X,dep_Y,6)       

acclin=[]
accsvml=[]
accdes=[]
accrf=[]

for i in rfelist:   
    
    X_train, X_test, y_train, y_test=split_scaler(i,dep_Y)   
   
    r2_lin=Linear(X_train,y_train,X_test,y_test)
    acclin.append(r2_lin)
    
    r2_svml=svm_linear(X_train,y_train,X_test,y_test)  
    accsvml.append(r2_svml)
    
    r2_des=Decision(X_train,y_train,X_test,y_test)  
    accdes.append(r2_des)
    
    r2_rf = random(X_train,y_train,X_test,y_test)  
    accrf.append(r2_rf)
    
result=rfe_regression(acclin,accsvml,accdes,accrf)

LinearRegression()
SVR(kernel='linear')
DecisionTreeRegressor(random_state=0)
RandomForestRegressor(n_estimators=10, random_state=0)

In [11]:
#3
result

                 Linear      SVMl  Decision    Random
Linear         0.441961  0.262153  0.441961  0.441816
SVC            0.441961  0.262153  0.441961  0.441816
Random         0.664893  0.609652  0.965961  0.916304
Decision Tree  0.676174  0.670691  0.933504  0.887256

In [15]:
#4 
result

                 Linear      SVMl  Decision    Random
Linear         0.604010  0.457046  0.776711  0.776492
SVC            0.604010  0.457046  0.776711  0.776492
Random         0.671727  0.628963  0.835247  0.840300
Decision Tree  0.681563  0.614992  0.967110  0.923559

In [13]:
#5
result

                 Linear      SVMl  Decision    Random
Linear         0.620124  0.457136  0.779240  0.780135
SVC            0.604508  0.456871  0.776474  0.776745
Random         0.674403  0.628206  0.696181  0.815538
Decision Tree  0.686361  0.643365  0.836806  0.845303

In [17]:
#6 
result

                 Linear      SVMl  Decision    Random
Linear         0.624738  0.456874  0.817230  0.814741
SVC            0.610294  0.530043  0.806415  0.807916
Random         0.697365  0.665248  0.782986  0.829427
Decision Tree  0.705126  0.670093  0.839675  0.875221

# Conclusion

***Based on the R2 scores of the models n = 4 features for RFE on decision tree for decision tree algorithm is best as it has the highest r2 score***